version: '3'
services:
    core_api:
        build: .
        container_name: "core-api-container"
        ports:
            - "80:15400"
        volumes:
            - ./backend/:/app
        restart: always